README.md
checkstyle-suppressions.xml
pom.xml
src/main/java/api/dto/PaginationDto.java
src/main/java/core/backend/ISearchService.java
src/main/java/core/backend/azure/cosmosdb/CosmosDbRepository.java
src/main/java/core/vertx/event/consumer/DownloadListener.java
src/main/resources/application.yml
src/main/webui/src/components/layout/Footer.tsx
src/main/webui/src/components/layout/__snapshots__/Footer.test.tsx.snap
src/main/webui/src/views/ModuleOverview.tsx
src/test/java/core/vertx/event/consumer/DownloadListenerTest.java

Add CosmosDb as backend closing #44

introduce CosmosDbRepository

---

pom.xml
src/main/resources/application.yml
src/main/webui/package.json
src/main/webui/src/components/layout/Footer.tsx
src/main/webui/src/components/layout/__snapshots__/Footer.test.tsx.snap

prepare release 0.2.2

---

docker-compose.yml

Localstack rolled out a new major version with breaking changes

adopt localstack 2.0

---

.github/workflows/build.yml
.github/workflows/deploy.yml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

Contributions file

---

changelog.adoc
pom.xml
src/main/resources/application.yml
src/main/webui/package.json
src/main/webui/src/components/layout/__snapshots__/Footer.test.tsx.snap

release 0.6.2

---

README.md
src/main/java/core/upload/service/FileService.java
src/main/java/extensions/docs/report/TerraformDocumentation.java

Support nested modules in modules

---

Brewfile
src/main/webui/src/components/documentation/ModuleInput.test.tsx
src/main/webui/src/components/documentation/ModuleInput.tsx
src/main/webui/src/components/documentation/__snapshots__/ModuleInput.test.tsx.snap
src/main/webui/src/components/tab/__snapshots__/ModuleAnalysis.test.tsx.snap
src/main/webui/src/types/index.ts
src/main/webui/src/views/ProviderDetails.tsx

Addresses findings in #364 and adds default values for module inputs

Improve module detail view

---

changelog.adoc
pom.xml
src/main/resources/application.yml
src/main/webui/package.json
src/main/webui/src/components/layout/__snapshots__/Footer.test.tsx.snap

Prepare release 0.6.3
Special thanks to @WeiMengXS who reported some bugs and issues

Release 0.6.3

---

changelog.adoc
pom.xml
src/main/resources/application.yml
src/main/webui/package.json
src/main/webui/src/components/layout/__snapshots__/Footer.test.tsx.snap

release 0.7.0

---

docs/CONTRIBUTING
docs/configuration.md

This pull request introduces a new document, `docs/CONTRIBUTING`, and makes changes to the `docs/configuration.md` file. The changes aim to provide clearer instructions for future contributors, and introduces more detailed information about the backend and storage configurations of the Tapir project.
Contributing Guidelines:
* [`docs/CONTRIBUTING`](diffhunk://#diff-5af86fb1fd306bf72602ce9bd3eb0ebdd5edade72093ea25565e3fb7dff620a0R1-R37): A new guide on how to contribute to the Tapir project has been added. This guide provides step-by-step instructions on how to fork the repository, create a new branch for changes, commit and push changes, and submit a pull request for review.
Configuration Details:
* [`docs/configuration.md`](diffhunk://#diff-17ed18489a956f326ec0fe4040850c5bc9261d4631fb42da …

Feature/Updating Docs

---

changelog.adoc
dev/docs/RUNBOOK.md
src/main/java/api/router/SpaRouter.java

introduce custom SPA router

---

examples/azure/containerapps/README.md
examples/azure/containerapps/data.tf
examples/azure/containerapps/db.tf
examples/azure/containerapps/providers.tf
examples/azure/containerapps/rg.tf
examples/azure/containerapps/sa.tf
examples/azure/containerapps/tapir.tf
examples/azure/containerapps/variables.tf
examples/azure/containerapps/vault.tf

Added a quick example for how to deploy Tapir to Container Apps on Azure.
Hopefully closes https://github.com/PacoVK/tapir/issues/47 .
Feel free to remove the `README.md` if you feel it is not necessary.
Please **delete** options that are **not** relevant.

docs: Add initial example for Azure Container Apps.

---

src/main/java/core/backend/azure/cosmosdb/CosmosDbRepository.java

Fix provider upload with CosmosDB backend

---

src/main/webui/package.json
src/main/webui/src/components/securityReportVisualization/__snapshots__/MisconfigurationItem.test.tsx.snap
src/main/webui/src/components/securityReportVisualization/__snapshots__/ReportFindings.test.tsx.snap
src/main/webui/yarn.lock

Upgrade some UI dependencies before release

upgrade dependencies

---

changelog.adoc
pom.xml
src/main/resources/application.yml
src/main/webui/package.json
src/main/webui/src/components/layout/__snapshots__/Footer.test.tsx.snap

release 0.8.0

---

src/main/java/core/backend/azure/cosmosdb/CosmosDbRepository.java

Fix Deploykeys not showing in UI

---

changelog.adoc
pom.xml
src/main/resources/application.yml
src/main/webui/package.json
src/main/webui/src/components/layout/__snapshots__/Footer.test.tsx.snap

Release 0.8.1

---

.github/workflows/build.yml

switch to "docker compose" in CI

---

changelog.adoc
pom.xml
src/main/resources/application.yml
src/main/webui/package.json
src/main/webui/src/components/forms/DeployKeyForm.tsx
src/main/webui/src/components/forms/__snapshots__/DeployKeyForm.test.tsx.snap
src/main/webui/src/components/layout/__snapshots__/Footer.test.tsx.snap

release 0.9.0

---

docker-compose.yml

upgrade to keycloak 26

---

changelog.adoc
pom.xml
src/main/resources/application.yml
src/main/webui/package.json
src/main/webui/src/components/layout/__snapshots__/Footer.test.tsx.snap

Release 0.9.1

---

changelog.adoc
pom.xml
src/main/resources/application.yml
src/main/webui/package.json
src/main/webui/src/components/layout/__snapshots__/Footer.test.tsx.snap

Release 0.9.3

---

docs/usage.md
src/main/java/core/service/VersionService.java
src/main/webui/src/components/layout/__snapshots__/Footer.test.tsx.snap
src/test/java/core/service/VersionServiceTest.java

We do neither enforce nor allow v- prefixes on modules and providers. see #477

fix version enforcement for modules and providers
